[project]
name = "redlog-py"
version = "0.1.0"
description = ""
authors = [
    {name = "redthing1",email = "redthing1@alt.icu"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
